# Generated by Django 5.1.4 on 2025-03-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0010_mnb_name_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tranzakciok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felhasznalonev', models.CharField(max_length=100)),
                ('kuldesdatuma', models.DateField(default='2025-03-05')),
                ('kedvezmenyezettneve', models.CharField(default='', max_length=100)),
                ('kedvezmenyezettszamlaszam', models.IntegerField(default=0)),
                ('elkuldottosszeg', models.FloatField()),
                ('elkuldottdevizanem', models.CharField(default='EUR', max_length=4)),
                ('megjegyzesek', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='mnb_name_good',
        ),
        migrations.DeleteModel(
            name='Valutak',
        ),
        migrations.AlterModelOptions(
            name='mnb_deviza',
            options={'verbose_name_plural': 'Valuta - Deviza'},
        ),
    ]
