# Generated by Django 5.1.4 on 2025-02-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0008_mnb_name_good'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Valutak',
        ),
        migrations.AlterModelOptions(
            name='mnb_deviza',
            options={'verbose_name_plural': 'MNBDeviza'},
        ),
        migrations.AlterModelOptions(
            name='mnb_name_good',
            options={'verbose_name_plural': 'Deviza nevek'},
        ),
    ]
