# Generated by Django 5.1.4 on 2025-02-20 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0009_delete_valutak_alter_mnb_deviza_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tranzakciok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('kuldesdatuma', models.DateTimeField(default=datetime.date(2025, 2, 20))),
                ('elkuldottosszeg', models.FloatField()),
                ('elkuldottdevizanem', models.CharField(max_length=4)),
                ('megjegyzesek', models.TextField()),
            ],
        ),
    ]
