# Generated by Django 5.1.4 on 2025-02-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0010_tranzakciok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tranzakciok',
            old_name='username',
            new_name='felhasznalonev',
        ),
        migrations.AlterField(
            model_name='tranzakciok',
            name='kuldesdatuma',
            field=models.DateField(default='2025-02-20'),
        ),
    ]
