# Generated by Django 5.1.4 on 2025-02-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0011_rename_username_tranzakciok_felhasznalonev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranzakciok',
            name='kedvezmenyezettneve',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tranzakciok',
            name='kedvezmenyezettszamlaszam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tranzakciok',
            name='kuldesdatuma',
            field=models.DateField(default='2025-02-22'),
        ),
    ]
