# Generated by Django 5.1.4 on 2025-02-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0012_tranzakciok_kedvezmenyezettneve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzakciok',
            name='kuldesdatuma',
            field=models.DateField(default='2025-02-24'),
        ),
        migrations.AlterField(
            model_name='tranzakciok',
            name='megjegyzesek',
            field=models.TextField(default=''),
        ),
    ]
