# Generated by Django 5.1.4 on 2025-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0013_alter_tranzakciok_kuldesdatuma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzakciok',
            name='elkuldottdevizanem',
            field=models.CharField(default='EUR', max_length=4),
        ),
        migrations.AlterField(
            model_name='tranzakciok',
            name='kuldesdatuma',
            field=models.DateField(default='2025-03-04'),
        ),
    ]
